config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  resources :estates do
    resources :bookings, only: [:new, :create]
  end

  resources :user do
    resources :bookings
  end

  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amenity.rb
class Amenity < ApplicationRecord
  has_many :estate_amenities
  has_many :estates, through: :estate_amenities
  validates :title, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :estate

  validates :start_date, uniqueness: true, presence: true
  validates :end_date, uniqueness: true, presence: true

  def overlaps?(booking)
    return true if booking.start_date.between?(self.start_date, self.end_date)
    return true if booking.end_date.between?(self.start_date, self.end_date)
    return true if booking.start_date < self.start_date && booking.end_date > self.end_date
    false
  end

end

app/models/booking_setting.rb
class BookingSetting < ApplicationRecord
  belongs_to :estate
end

app/models/estate.rb
class Estate < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :estate_amenities, dependent: :destroy
  has_many :amenities, through: :estate_amenities
  has_one :owner, class_name: "User"
  has_attachments :photos, maximum: 50

  def dates_booked
    h = []
    h = bookings.map{ |booking| booking.start_date }
    self.bookings.each do |b_end_date|
      h << b_end_date.end_date
    end
    return h
  end

  def unavailable_dates
    dates_booked
  end

  private



end

app/models/estate_amenity.rb
class EstateAmenity < ApplicationRecord
  belongs_to :estate
  belongs_to :amenity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :estates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/booking_settings_controller.rb
class BookingSettingsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @estate = Estate.find(params[:estate_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.estate = Estate.find(params[:estate_id])
    @booking.status = "pending"
    if @booking.save
      redirect_to :root
    else
      :new
    end

  end

  private

  def booking_params
    params.require(:booking).permit(:user, :estate, :start_date, :end_date)
  end

end

app/controllers/estates_controller.rb
class EstatesController < ApplicationController
  def index
    @estates = Estate.all
  end

  def show
    @estate = Estate.find(params[:id])
  end

  def new
    @estate = Estate.new
  end

  def create
    @estate = Estate.new(estate_params)
    @estate.user = current_user
    if @estate.save
      redirect_to estate_path(@estate)
    else
      render :new
    end
  end

  def edit
    @estate = Estate.find(params[:id])
  end

  def update
    @estate = Estate.find(params[:id])
    @estate.update(estate_params)
    redirect_to estate_path(@estate)
  end

  def destroy
    @estate = Estate.find(params[:id])
    @estate.destroy
    redirect_to estate_path
  end

  def disable
    @estate = Estate.find(params[:id])
    @estate.disable = true
  end

  private

  def estate_params
    params.require(:estate).permit(
      :name,
      :description,
      :minimum_reservation_span,
      :must_have_weekend,
      photos: []
    )
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/booking_settings/index.html.erb
<h1>BookingSettings#index</h1>
<p>Find me in app/views/booking_settings/index.html.erb</p>

app/views/booking_settings/show.html.erb
<h1>BookingSettings#show</h1>
<p>Find me in app/views/booking_settings/show.html.erb</p>

app/views/bookings/_form.html.erb
<div class="container">
  <%= simple_form_for [@estate, @booking] do |f| %>
  <div class="form-group">
    <%= f.input :start_date, input_html: {class: "form-control"} %>
    <%= f.input :end_date, input_html: {class: "form-control"} %>

  </div>
  <%= f.submit %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<%= render 'form' %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/estates/_form.html.erb
<!-- RD Mailform-->
<%= simple_form_for @estate, defaults: {input_html: {class: 'form-control'}, label_html: {class: 'form-label form-label-outside'} } do |f| %>
<section class="section-xxs bg-white text-left">
  <div class="shell rd-mailform">
    <div class="cell-xs-12">
      <%= f.input :name, placeholder: "Enter the estate name", label: 'Estate name', required: true, error: 'Estate must have a name.', wrapper_html: {class: 'form-wrap'} %>
    </div>

    <div class="cell-xs-12">
      <%= f.input :description, as: :text, label: 'Description', input_html: {class: 'form-input form-control-has-validation'}, wrapper_html: {class: 'form-wrap'} %>
    </div>

    <div class="cell-xs-12">
      <%= f.input :photos, as: :attachinary, wrapper_html: {class: 'form-wrap'} %>
    </div>
  </div>
</section>
<section class="section-xxs bg-white text-left">
  <div class="shell rd-mailform">
    <h4>Booking Reservation Criteria:</h4>

    <div class="cell-xs-12">
      <%= f.input :minimum_reservation_span, label: 'Minimum Reservation Span', as: :integer, hint: 'ie: 7 days', wrapper_html: {class: 'form-wrap'}  %>
    </div>
    <div class="cell-xs-12">
      <%= f.input :must_have_weekend, label: 'Must spend weekend' , as: :radio_buttons, hint: 'Booking against this estate must spend one weekend.', wrapper_html: {class: 'form-wrap'}  %>
    </div>
  </div>
</section>

<!-- Page Footer-->
<section class="section-xxs bg-white text-left">
<div class="shell rd-mailform">
  <div class="cell-xs-12">
    <h4>Location & Ammenities</h4>
  </div>
</div>
</section>
<footer class="page-footer-corporate object-wrap object-wrap-md-left object-wrap-map bg-gray-dark text-left">
  <div class="object-wrap-body object-wrap-map sizing-1">
    <!-- RD Google Map-->
    <div class="rd-google-map rd-google-map__model" data-zoom="15" data-x="-73.9874068" data-y="40.643180">
      <ul class="map_locations">
        <li data-y="40.643180" data-x="-73.9874068">
          <p>9870 St Vincent Place, Glasgow, DC 45 Fr 45.</p>
        </li>
      </ul>
    </div>
  </div>
  <div class="shell">
    <div class="range range-sm-right">
      <div class="cell-md-6">
        <div class="page-footer-corporate-inner">
          <div class="page-footer-corporate-top range range-60">
            <div class="cell-sm-6 cell-md-12 wow fadeInUp" data-wow-delay=".1s">
              <h5>Amenities</h5>
              <hr class="divider divider-sm divider-left">
              <%= f.association :amenities, collection: Amenity.order(:title), prompt: "Choose a Company", as: :check_boxes %>
            </div>
            <div class="cell-sm-6 cell-md-12 wow fadeInUp" data-wow-delay=".1s">
              <h5>Other settings</h5>
              <hr class="divider divider-sm divider-left">
              <div class="group">
                <dl class="list-desc">
                  <dt>Weekdays: </dt>
                  <dd><span>8:00–20:00</span></dd>
                </dl>
                <dl class="list-desc">
                  <dt>Weekends: </dt>
                  <dd><span>9:00–18:00</span></dd>
                </dl>
              </div>
            </div>
            <div class="cell-sm-6 cell-md-12 wow fadeInUp" data-wow-delay=".1s">
              <h5>Navigation</h5>
              <hr class="divider divider-sm divider-left">
              <ul class="nav-list list-column-3">
                <li><a class="link" href="index.html">Home</a></li>
                <li><a class="link" href="about-us.html">About Us</a></li>
                <li><a class="link" href="grid-gallery.html">Gallery</a></li>
                <li><a class="link" href="services.html">Services</a></li>
                <li><a class="link" href="contacts.html">Location</a></li>
                <li><a class="link" href="specials.html">Specials</a></li>
              </ul>
            </div>
          </div>
          <div class="page-footer-corporate-bottom wow fadeInUp" data-wow-delay=".1s">
            <div class="group"><span>Follow Us:</span>
              <ul class="list-inline">
                <li><a class="icon icon-sm icon-gray-3 fa fa-instagram" href="#"></a></li>
                <li><a class="icon icon-sm icon-gray-3 fa fa-facebook" href="#"></a></li>
                <li><a class="icon icon-sm icon-gray-3 fa fa-twitter" href="#"></a></li>
              </ul>
            </div>
            <p class="rights">Royal Villas&nbsp;&copy;&nbsp;<span id="copyright-year"></span>.&nbsp;<br class="veil-sm"><a class="link-underline" href="privacy-policy.html">Privacy Policy</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
<section class="section-xxs bg-white text-center">
  <div class="shell rd-mailform">
    <div class="cell-xs-12">
      <%= f.button :submit, class: 'button button-primary button-square button-block button-effect-ujarak' %>
    </div>
  </div>
</section>
<% end %>

app/views/estates/edit.html.erb
<%= render 'form' %>

app/views/estates/index.html.erb
<h1>Estates</h1>
<%= link_to "Create New Estate", new_estate_path %>
<ul>
  <% @estates.each do |estate| %>
    <li>
      <%= cl_image_tag estate.photos.first.path %>
      <%= estate.name  %>
      <%= link_to estate.name, estate_path(id: estate.id) %>
      | <%= link_to "Delete", estate_path(id: estate.id), method: :delete %>
    </li>
  <% end %>
</ul>
<section class="section section-md bg-white element-mod">
          <div class="shell">
            <div class="range range-xs-center range-md-justify range-30">
              <div class="cell-sm-7 cell-md-6">
                <div class="img-thumbnail-custom"><img class="img-responsive" src="images/team-mp-01-570x569.jpg" alt="" width="570" height="569"/>
                  <div class="caption">
                    <ul class="list-inline list-inline-sm">
                      <li>
                        <div class="unit unit-horizontal unit-middle unit-spacing-xs">
                          <div class="unit__left"><span class="icon icon-sm text-gray-darker mdi mdi-phone text-middle"></span></div>
                          <div class="unit__body"><a class="link-gray" href="callto:#">+ 123 098 890 76 56</a></div>
                        </div>
                      </li>
                      <li>
                        <div class="unit unit-horizontal unit-middle unit-spacing-xs">
                          <div class="unit__left"><span class="icon icon-sm text-gray-darker mdi mdi-email-outline text-middle"></span></div>
                          <div class="unit__body"><a class="link-gray" href="mailto:#">ts@demolink.org</a></div>
                        </div>
                      </li>
                      <li><a class="button button-gray-dark-outline button-square button-effect-ujarak" href="contacts.html"><span>Get in touch</span></a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="cell-sm-7 cell-md-5 text-sm-left">
                <h3>Theresa Smith</h3>
                <div class="team-member-position"><span>General Manager</span></div>
                <p>Theresa is our eyes and ears. You will rarely see her without radio,  walking the grounds, making sure everyone is happy and taken care of.</p>
                <!-- Blockquote default-->
                <div class="quote-default quote-default-left">
                  <div class="quote-body">
                    <div class="unit unit-xs-horizontal unit-xs-top unit-spacing-sm">
                      <div class="unit__left">
                        <svg x="0px" y="0px" width="37px" height="27px" viewbox="0 0 37 27">
                          <path d="M16.916,18.73c0,2.351-0.833,4.319-2.499,5.901C12.754,26.208,10.786,27,8.516,27  c-2.268,0-4.255-0.792-5.96-2.369c-1.703-1.582-2.552-3.477-2.552-5.679c0-2.208,1.022-4.891,3.064-8.054L9.879-0.018h6.585  l-4.202,11.471C15.365,12.847,16.916,15.275,16.916,18.73z M36.99,18.73c0,2.351-0.833,4.319-2.499,5.901  C32.828,26.208,30.86,27,28.588,27c-2.269,0-4.256-0.792-5.959-2.369c-1.702-1.582-2.555-3.477-2.555-5.679  c0-2.208,1.025-4.891,3.066-8.054l6.813-10.916h6.581l-4.197,11.471C35.437,12.847,36.99,15.275,36.99,18.73z"></path>
                        </svg>
                      </div>
                      <div class="unit__body">
                        <p class="quote-default-title">
                          <q>I’m glad to be a part of this spa resort. It has a very friendly team and a great atmosphere.</q>
                        </p>
                      </div>
                    </div>
                  </div>
                  <div class="quote-footer">
                    <cite></cite>
                  </div>
                </div>
                <p>She is dedicated to customer service and makes sure every guest is treated like family from arrival to departure, always remembering names and guest facts for each person that passes through the spa resort.</p>
                <ul class="list-bars">
                  <li class="list-bars-item">
                    <!-- Progress Bar-->
                    <div class="progress-bar-bs progress-variant-primary">
                      <p class="list-bars-item-header">commitment</p>
                      <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%;"></div>
                      </div><span class="caption">75%</span>
                    </div>
                  </li>
                  <li class="list-bars-item">
                    <!-- Progress Bar-->
                    <div class="progress-bar-bs progress-variant-primary">
                      <p class="list-bars-item-header">responsibility</p>
                      <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 85%;"></div>
                      </div><span class="caption">85%</span>
                    </div>
                  </li>
                  <li class="list-bars-item">
                    <!-- Progress Bar-->
                    <div class="progress-bar-bs progress-variant-primary">
                      <p class="list-bars-item-header">hospitality</p>
                      <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%;"></div>
                      </div><span class="caption">80%</span>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section class="section section-md bg-gray-light">
          <div class="shell">
            <h3>Rooms & Suites</h3>
            <p>Royal Villas offers the finest accommodations with unique designs that provide both a luxurious and relaxing environment. Specially <br> selected fabrics and finishes vary from room to room, offering guests a variety of beautiful and unique atmospheres to select from.</p>
            <div class="range range-30" data-photo-swipe-gallery="gallery">
              <div class="cell-sm-6 cell-md-4"><a class="thumbnail-classic" href="images/grid-gallery-1-1200x800_original.jpg" data-photo-swipe-item="" data-size="1200x800">
                  <figure><img src="images/grid-gallery-1-370x276.jpg" alt="" width="370" height="276"/>
                  </figure>
                  <div class="caption">
                    <p class="caption-title">Luxury Suites</p>
                    <p class="caption-text">Each suite has its own unique décor and arrangement.</p>
                  </div></a>
              </div>
              <div class="cell-sm-6 cell-md-4"><a class="thumbnail-classic" href="images/grid-gallery-2-1200x800_original.jpg" data-photo-swipe-item="" data-size="1200x800">
                  <figure><img src="images/grid-gallery-2-370x276.jpg" alt="" width="370" height="276"/>
                  </figure>
                  <div class="caption">
                    <p class="caption-title">Comfortable Accommodation</p>
                    <p class="caption-text">Each suite has its own unique décor and arrangement.</p>
                  </div></a>
              </div>
              <div class="cell-sm-6 cell-md-4"><a class="thumbnail-classic" href="images/grid-gallery-3-1058x800_original.jpg" data-photo-swipe-item="" data-size="1058x800">
                  <figure><img src="images/grid-gallery-3-370x276.jpg" alt="" width="370" height="276"/>
                  </figure>
                  <div class="caption">
                    <p class="caption-title">Cozy Atmosphere</p>
                    <p class="caption-text">Each suite has its own unique décor and arrangement.</p>
                  </div></a>
              </div>
              <div class="cell-sm-6 cell-md-4"><a class="thumbnail-classic" href="images/grid-gallery-4-1200x797_original.jpg" data-photo-swipe-item="" data-size="1200x797">
                  <figure><img src="images/grid-gallery-4-370x276.jpg" alt="" width="370" height="276"/>
                  </figure>
                  <div class="caption">
                    <p class="caption-title">Luxury Suites</p>
                    <p class="caption-text">Each suite has its own unique décor and arrangement.</p>
                  </div></a>
              </div>
              <div class="cell-sm-6 cell-md-4"><a class="thumbnail-classic" href="images/grid-gallery-5-1200x800_original.jpg" data-photo-swipe-item="" data-size="1200x800">
                  <figure><img src="images/grid-gallery-5-370x276.jpg" alt="" width="370" height="276"/>
                  </figure>
                  <div class="caption">
                    <p class="caption-title">Comfortable Accommodation</p>
                    <p class="caption-text">Each suite has its own unique décor and arrangement.</p>
                  </div></a>
              </div>
              <div class="cell-sm-6 cell-md-4"><a class="thumbnail-classic" href="images/grid-gallery-6-1200x800_original.jpg" data-photo-swipe-item="" data-size="1200x800">
                  <figure><img src="images/grid-gallery-6-370x276.jpg" alt="" width="370" height="276"/>
                  </figure>
                  <div class="caption">
                    <p class="caption-title">Cozy Atmosphere</p>
                    <p class="caption-text">Each suite has its own unique décor and arrangement.</p>
                  </div></a>
              </div>
            </div>
          </div>
        </section>

app/views/estates/new.html.erb
<h4>Add a new estate</h4>
  <%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">
  <head>
    <!-- Site Title-->
    <title>Home</title>
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic%7CPoppins:300,400,500,700">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <!--[if lt IE 10]>
    <div style="background: #212121; padding: 10px 0; box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3); clear: both; text-align:center; position: relative; z-index:1;"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="ie8-panel/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <script src="js/html5shiv.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <!-- Javascript-->
    <script type="text/javascript">
     var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-7078796-5']);
      _gaq.push(['_trackPageview']);
      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 </div>
    <!-- PANEL-->
    <!-- END PANEL-->
    <!-- Global Mailform Output-->
    <div class="snackbars" id="form-output-global"></div>
    <!-- PhotoSwipe Gallery-->
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="pswp__bg"></div>
      <div class="pswp__scroll-wrap">
        <div class="pswp__container">
          <div class="pswp__item"></div>
          <div class="pswp__item"></div>
          <div class="pswp__item"></div>
        </div>
        <div class="pswp__ui pswp__ui--hidden">
          <div class="pswp__top-bar">
            <div class="pswp__counter"></div>
            <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
            <button class="pswp__button pswp__button--share" title="Share"></button>
            <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
            <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
            <div class="pswp__preloader">
              <div class="pswp__preloader__icn">
                <div class="pswp__preloader__cut">
                  <div class="pswp__preloader__donut"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
            <div class="pswp__share-tooltip"></div>
          </div>
          <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
          <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
          <div class="pswp__caption">
            <div class="pswp__caption__cent"></div>
          </div>
        </div>
      </div>
    </div>

app/views/shared/_navbar.html.erb
    <!-- Page-->
    <div class="text-center page">
      <!-- Page Header-->
      <header class="page-header" style="padding-bottom: 24px;">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar rd-navbar-default-with-top-panel" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fullwidth" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-fullwidth" data-lg-device-layout="rd-navbar-fullwidth" data-md-stick-up-offset="90px" data-lg-stick-up-offset="150px" data-stick-up="true" data-sm-stick-up="true" data-md-stick-up="true" data-lg-stick-up="true">
            <div class="rd-navbar-top-panel rd-navbar-collapse">
              <div class="rd-navbar-top-panel-inner">
                <div class="left-side">
                  <div class="group"><span class="text-italic">Follow Us:</span>
                    <ul class="list-inline">
                      <li><a class="icon icon-sm icon-secondary-5 fa fa-instagram" href="#"></a></li>
                      <li><a class="icon icon-sm icon-secondary-5 fa fa-facebook" href="#"></a></li>
                      <li><a class="icon icon-sm icon-secondary-5 fa fa-twitter" href="#"></a></li>
                    </ul>
                  </div>
                </div>
                <div class="center-side">
                  <!-- RD Navbar Brand-->
                  <div class="rd-navbar-brand fullwidth-brand">
                    <%= link_to root_path, class: "brand-name" do %>
                      <%= image_tag "logo-default-280x48.png", width: 280, height: 48 %>
                    <% end %>
                  </div>
                </div>
                <div class="right-side">
                  <!-- Contact Info-->
                  <div class="contact-info">
                    <div class="unit unit-middle unit-horizontal unit-spacing-xs">
                      <div class="unit__left"><span class="icon icon-primary text-middle mdi mdi-phone"></span></div>
                      <div class="unit__body">
                        <% if user_signed_in? %>
                          <%= link_to destroy_user_session_path, method: :delete do %>
                            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                          <% end %>
                        <% else %>
                          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "text-middle" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="rd-navbar-inner">
              <!-- RD Navbar Panel-->
              <div class="rd-navbar-panel">
                <!-- RD Navbar Toggle-->
                <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                <!-- RD Navbar collapse toggle-->
                <button class="rd-navbar-collapse-toggle" data-rd-navbar-toggle=".rd-navbar-collapse"><span></span></button>
                <!-- RD Navbar Brand-->
                <div class="rd-navbar-brand mobile-brand"><a class="brand-name" href="index-2.html">
                  <%= image_tag "logo-default-left-245x42.png", width: 245, height: 42 %></a></div>
              </div>
              <div class="rd-navbar-aside-right">
                <div class="rd-navbar-nav-wrap">
                  <div class="rd-navbar-nav-scroll-holder">
                    <ul class="rd-navbar-nav">
                      <li class="active">
                        <%= link_to "Home", root_path %>
                      </li>
                      <li><%= link_to "Estates", estates_path %>
                      </li>
                      <li><a href="#">Locations</a>
                        <ul class="rd-navbar-dropdown">
                          <li>
                            <a href="services.html">England</a>
                          </li>
                          <li>
                            <a href="services.html">France</a>
                          </li>
                        </ul>
                      </li>

                      <li><a href="contacts.html">Contacts</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>